<?php

    function helix_menu()
    {
        $items['helix'] = array(
            'title' => 'Helix',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('helix_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        $items['helix_success_page'] = array(
            'title' => 'DNA Helix Results',
            'page callback' => 'helix_output',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function helix_form()
    {
        $form['dnainput'] = array(
            '#title' => 'Enter one half of the double helix',
            '#type' => 'textfield',
            '#element_validate' => array('element_validate_input'),
            '#required' => TRUE,
        );

        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Submit',
        );
        return $form;
    }

    function element_validate_input($element)
    {
        $valid_char = array('A', 'T', 'C', 'G');
        $letters = str_split(strtoupper($element['#value']));
        foreach($letters as $each_letter) {
            if (in_array($each_letter, $valid_char) == false) {
                form_error($element, t('Please enter only A, T, C or G'));
            }
        }
    }

    function dna_helix($input)
    {
        $input_array = str_split($input);
        $output = array();

        foreach ($input_array as &$letter) {
            if($letter == "A") {
                array_push($output, "T");
            } elseif ($letter == "T") {
                array_push($output, "A");
            } elseif ($letter == "C") {
                array_push($output, "G");
            } elseif ($letter == "G") {
                array_push($output, "C");
            }
        }
        // $output = implode("", $output);
        return implode("", $output);
    }

    function helix_form_submit($form, &$form_state)
    {
        $input = strtoupper($form_state['values']['dnainput']);
        $_SESSION['first_half'] = $input;
        $result = dna_helix($input);
        $_SESSION['second_half'] = $result;
        $form_state['redirect'] = 'helix_success_page';
    }

    function helix_output()
    {
        return '<h3>First half of the double helix: <span class="red">' . $_SESSION['first_half'] . '</span><br>' .
                'Second half of the double helix: <span class="blue">' . $_SESSION['second_half'] . '</span></h3>';
    }
