<?php

    function helix_menu()
    {
        $items['helix'] = array(
            'title' => 'Helix',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('helix_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        $items['helix_success_page'] = array(
            'title' => 'DNA Helix Results',
            'page callback' => 'helix_output',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function helix_form()
    {
        $form['dnainput'] = array(
            '#title' => 'Enter one half of the double helix',
            '#type' => 'textfield',
            '#required' => TRUE,
        );

        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Submit',
        );
        return $form;
    }

    function dna_helix($input)
    {
        $input_array = str_split($input);
        $output = array();

        foreach ($input_array as &$letter) {
            if($letter == "A") {
                array_push($output, "T");
            } elseif ($letter == "T") {
                array_push($output, "A");
            } elseif ($letter == "C") {
                array_push($output, "G");
            } elseif ($letter == "G") {
                array_push($output, "C");
            }
        }
        // $output = implode("", $output);
        return implode("", $output);
    }

    function helix_form_submit($form, &$form_state)
    {
        $input = strtoupper($form_state['values']['dnainput']);
        $_SESSION['first_half'] = $input;
        $result = dna_helix($input);
        $_SESSION['second_half'] = $result;
        $form_state['redirect'] = 'helix_success_page';
    }

    function helix_output()
    {
        return '<h2>First half of the double helix: ' . $_SESSION['first_half'] . '<br>' .
                'Second half of the double helix: ' . $_SESSION['second_half'] . '</h2>';
    }
